
# Hierarchical Clustering

**Distance measure**: `r input$hc_dist_method`

**Agglomeration method**: `r input$hc_agglo_method`

```{r echo = FALSE, warning=FALSE, message = FALSE, fig.width = 12, fig.height = 7}
# distance measure
hcList <- callModule(pivot_dataScale, "hc_scale", r_data)

    if(input$hclust_package != "networkD3") {
par(mar=c(8, 8, 8, 8), cex = 1, xpd=TRUE)

    if(is.null(r_data$hc)) return ()
    hc0 <- r_data$hc
    # get max height of the tree, this will be used to adjust the group bar height
   max_height <- max(hc0$height)
    hc1 <- hc0 %>% as.dendrogram()
    # Cut tree to get cluster
    r_data$meta$hierarchical_cluster <- as.character(dendextend::cutree(hc1, k = input$hclust_num))

    rsList <- callModule(pivot_groupBy, "hclust", meta = r_data$meta)
    if(is.null(rsList$meta)) {
        plot(hc1)
    } else {
        # extract meta data
        meta <- rsList$meta
        meta_color <- rsList$meta_color

        if (length(rsList$group_by) == 1) {
            #assign("hc1", hc1, env= .GlobalEnv)
            selected_color <- as.character(meta_color[,1])
            dendextend::labels_colors(hc1) <- selected_color[order.dendrogram(hc1)]
            plot(hc1)
            dendextend::colored_bars(colors = meta_color, dend = hc1, rowLabels = rsList$group_by)
            legend("topright", inset = c(-0.1,0), legend = unique(meta[,1]),  bty="n",
                   title = colnames(meta)[1], title.col = "black", cex = 1,
                   fill = unique(selected_color), text.col = unique(selected_color), border = FALSE)
        } else if (length(rsList$group_by) <= 5){
            plot(hc1)
            dendextend::colored_bars(colors = meta_color, dend = hc1, rowLabels = rsList$group_by)
            inset_h = 0
            for(i in 1: length(rsList$group_by)) {
                legend("topright", inset = c(-0.1, inset_h), legend = unique(meta[,i]),
                       title = colnames(meta)[i], title.col = "black", cex = 1, bty="n",
                       fill = unique(as.character(meta_color[,i])), text.col = unique(as.character(meta_color[,i])), border = F)
                inset_h = inset_h + 0.15 +0.057 * length(unique(meta[,i]))
            }
        } else {
            session$sendCustomMessage(type = "showalert", "Unable to plot more than 5 categories.")
            return()
        }
    }
    if(input$hclust_show){
        hc1 %>% dendextend::rect.dendrogram(k=input$hclust_num, border = 8, lty = 5, lwd = 2)
    }
    } else {
        if(is.null(r_data$hc)) return ()
    Root <- r_data$hc

    rsList <- callModule(pivot_groupBy, "hclust", meta = r_data$meta)
    if(is.null(rsList$meta)) {
        networkD3::dendroNetwork(Root, fontSize = 15, treeOrientation = input$hc_dd_ori, linkColour = 'navyblue', nodeColour = 'grey', textOpacity = 1, opacity = 1, zoom = T, linkType = input$hc_dd_link_type)
    } else {
        # extract meta data
        meta <- rsList$meta
        meta_color <- rsList$meta_color

        if (length(rsList$group_by) == 1) {
            #assign("hc1", hc1, env= .GlobalEnv)
            selected_color <- as.character(meta_color[,1])
        } else {
            return(NULL)
        }
        networkD3::dendroNetwork(Root, fontSize = 15, textColour = selected_color, treeOrientation = input$hc_dd_ori, linkColour = 'navyblue', nodeColour = 'grey', textOpacity = 1, opacity = 1,  zoom = T, linkType = input$hc_dd_link_type)
    }
    }
```


```{r echo = FALSE, warning=FALSE, message = FALSE, fig.width = 8, fig.height = 6}
if(is.null(r_data$meta$hierarchical_cluster)) return()
    gList <- callModule(pivot_groupBy, "hclust2", meta = r_data$meta)

    if(is.null(gList$meta) || length(unique(gList$meta[,1])) == 0)
    {
        tbl <- r_data$meta[,c(1, which(colnames(r_data$meta) == "hierarchical_cluster"))]
    } else {
        actual_group <- gList$meta[,1]
        names(actual_group) <- r_data$sample_name
        tbl <- data.frame(actual_group)
        tbl$assigned_cluster <- r_data$meta$hierarchical_cluster
    }
    DT::datatable(tbl)
```

