
# Principal Component Analysis (PCA)

## PCA Summary

```{r echo = FALSE, warning=FALSE, message = FALSE}
if(is.null(r_data$pca)) return ()
    DT::datatable(summary(r_data$pca)$importance, options = list(scrollX = TRUE, scrollY = "210px", searching=F))
```

### Scree Plot

```{r echo = FALSE, warning=FALSE, message = FALSE, fig.width = 8, fig.height = 6}
if(is.null(r_data$pca)) return()
    pca_var <- data.frame(pcomp=1:length(r_data$pca$sdev), variances=r_data$pca$sdev^2)
    pca_var$variance_explained <- pca_var$variances / sum(pca_var$variances) * 100
    pca_var$cumulative_variance_explained <- cumsum(pca_var$variance_explained)
    pca_var %>% plotly::plot_ly(x = ~pcomp, y = ~variance_explained, type = "bar")
```

## PCA Loading

```{r echo = FALSE, warning=FALSE, message = FALSE}
if(is.null(r_data$pca)) return ()
    DT::datatable(r_data$pca$rotation, options = list(scrollX = TRUE, scrollY = "210px"))
```

## PCA Projection

```{r echo = FALSE, warning=FALSE, message = FALSE}
if (is.null(r_data$pca)) return()
    DT::datatable(t(r_data$pca$x), options = list(scrollX = TRUE, scrollY = "210px", searching=T))
```
    
## PCA Projection Plots

```{r echo = FALSE, warning=FALSE, message = FALSE}
    pca_minfo<- reactive(callModule(pivot_groupBy, "pca", meta = r_data$meta))
```

### 1D Projection

```{r echo = FALSE, warning=FALSE, message = FALSE, fig.width = 8, fig.height = 6}
    callModule(pivot_Plot1d, "pca_plot1d", type = "pca", r_data$pca, as.data.frame(r_data$pca$x), minfo = pca_minfo())
```

### 2D Projection

```{r echo = FALSE, warning=FALSE, message = FALSE, fig.width = 8, fig.height = 6}
    callModule(pivot_Plot2d, "pca_plot2d", type = "pca", r_data$pca, as.data.frame(r_data$pca$x), minfo = pca_minfo())
```

### 3D Projection

```{r echo = FALSE, warning=FALSE, message = FALSE, fig.width = 8, fig.height = 6}
    callModule(pivot_Plot3d, "pca_plot3d", type = "pca", r_data$pca, as.data.frame(r_data$pca$x), minfo = pca_minfo())
```

