---
title: "General Information"
output: html_document
---

### PIVOT: Platform for Interactive Analysis and Visualization of Transcriptomics Data v1.0.0

* This program is developed based on the Shiny framework, a set of R packages and a collection of scripts written by members of Junhyong Kim Lab at University of Pennsylvania. Its goal is to facilitate fast and interactive RNA-Seq data analysis and visualization. 

* This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 
* Script Contributors:

    <a href="mailto:hdueck@mail.med.upenn.edu" class="btn btn-primary">Hannah Dueck</a> (Clustering, heatmaps, densityScatter, ERCC distribution, Mann–Whitney U test)

    <a href="mailto:s.a.middlet@gmail.com"  class="btn btn-primary">Sarah Middleton</a> (PCA, clustering, heatmaps, t-SNE, Normalization, ERCC detecton probablity)
    
    <a href="mailto:safisher@sas.upenn.edu" class="btn btn-primary">Stephen Fisher</a> (rankFreq, pairwise-correlation, DESeq)
    
    <a href="mailto:mugdhak@mail.med.upenn.edu" class="btn btn-primary">Mugdha Khaladkar</a> (Modified DESeq)
    
    <a href="mailto:qinzhu@outlook.com" class="btn btn-primary">Qin Zhu</a> (GUI, interactivity)
    
* Principal Investigator:

     <a href="mailto:junhyong@sas.upenn.edu" class="btn btn-primary">Junhyong Kim</a> 

* Special thanks to Jennifer Spaethling, Derek Stefanik, Jamie Shallcross and Gehoon Chung for testing and suggestions. 

* Bug report, suggestions, script contribution and other related stuffs please contact <a href="mailto:qinzhu@outlook.com">*Qin Zhu* </a>.


<br>
<br>
